### ISSUE TITLE
Recieved a timeout error from listen

### ISSUE THREAD

**Issue by mehcode** [Schmavery/facebook-chat-api#147] opened 2016-01-12 02:34 UTC
```
ERR! ERROR in listen -->  Error: ETIMEDOUT
ERR! ERROR in listen -->      at null._onTimeout (/srv/node_modules/request/request.js:761:15)
ERR! ERROR in listen -->      at Timer.listOnTimeout (timers.js:92:15)
ERR! ERROR in listen -->   { [Error: ETIMEDOUT]
ERR! ERROR in listen -->    cause: { [Error: ETIMEDOUT] code: 'ETIMEDOUT', connect: false },
ERR! ERROR in listen -->    isOperational: true,
ERR! ERROR in listen -->    code: 'ETIMEDOUT',
ERR! ERROR in listen -->    connect: false }
```

What do you think is the cause of this? Any ideas? Maybe we should implement exponential back-off and retry a few times before erroring?

**Comment by Schmavery** [comment] 2016-01-12 03:07
Can you confirm that you continue to receive messages after receiving this error?  This is a duplicate of #89 and we're planning to simply suppress this error.

**Comment by mehcode** [comment] 2016-01-12 16:15
@Schmavery Can confirm. I do continue to receive messages. Strange that facebook errors for no sane reason.

**Comment by Schmavery** [comment] 2016-01-12 17:08
OK great thanks.  I'm going to close this now since #89 is already tracking this issue.

**Closed by Schmavery** 2016-01-12 17:08 UTC
Labels: duplicate
