### ISSUE TITLE
If I remove someone from a chat and re add them they can't talk

### ISSUE THREAD

**Issue by miketamis** [Schmavery/facebook-chat-api#62] opened 2015-08-28 03:13 UTC
If I remove some from the group and then add them back the person can't talk with the message "You cannot reply to this covensation", until I remove and readd the bot.

**Comment by jackwilsdon** [comment] 2015-08-28 03:33
That is Facebook themselves. I have this when in group chats. If you
Refresh the window, you can talk again.

**Comment by Schmavery** [comment] 2015-08-30 01:05
@jackwilsdon is this something we're missing in the api here?
I don't quite understand the problem, you after removing and readding a person, they can't talk until you remove and readd them again?

**Comment by bsansouci** [comment] 2015-09-13 04:10
Closing this because we can't reproduce it. It seems like an issue that's unrelated to the api. If you refresh after being added back, you _can_ talk.

**Closed by bsansouci** 2015-09-13 04:10 UTC
Labels: unconfirmed
