### ISSUE TITLE
Problem with login, cookies not enabled

### ISSUE THREAD

**Issue by roman30098** [Schmavery/facebook-chat-api#177] opened 2016-02-16 20:45 UTC
Hi, i've problem with login into my test fb account.
Node v4.3.0
npm v2.14

I using example code:
```js
var login = require("facebook-chat-api");
 
// Create simple echo bot 
login({email: "tisu11@wp.pl", password: "11usit"}, function callback (err, api) {
//email and password are real
    if(err) return console.error(err);
 
    api.listen(function callback(err, message) {
        api.sendMessage(message.body, message.threadID);
    });
});
```
But it always throw error "Wrong username/password".
I tried with 2 fb accounts on windows7 and ubuntu14.
"Kassy" don't work too.
Can somebody try to login with my login/psswd?

**Comment by Schmavery** [comment] 2016-02-16 21:15
Your email/pass works for me using the API.  Which version of the API are you on?  Does it work when you log in in the browser?
Is anyone else encountering this problem?

**Comment by roman30098** [comment] 2016-02-16 21:25
> "version": "1.0.6"
I can log in in browser, but can't with fb-chat-api.
If my login data work for you, i guess it may be problem with nodejs.
I've added firewall exception for node, npm works, so internet connection is ok.
You execute test code locally on computer or on web server?

**Comment by Schmavery** [comment] 2016-02-16 22:25
I just tested specifically with your data and version 1.0.6 locally on my computer, and it worked for me.  Curious to know what is causing this problem.

Can you add 
```js
require("fs").writeFileSync("log.txt", res.body + "\n\nHEADERS:::\n" + JSON.stringify(res.headers), "utf-8")
```
right after [line 150 of index.js](https://github.com/Schmavery/facebook-chat-api/blob/master/index.js#L151)?

**Comment by roman30098** [comment] 2016-02-17 00:19
Facebook says 
> Cookies Requires
> Cookies are not enabled on your browser. Please enable cookies in your browser preferences to continue.

Full log.txt:
[log.txt](https://github.com/Schmavery/facebook-chat-api/files/133466/log.txt)

Log from Ubuntu is almost the same.

**Comment by Schmavery** [comment] 2016-03-02 09:34
Is this still a problem?  I'm not sure what could be causing this, maybe an issue with the `request` module?  You could try deleting your node_module folder and reinstalling...
Otherwise Facebook could be rolling out a new cookie that we don't handle.  In that case, it would be useful for you to email us credentials to a test account where this issue can be reproduced consistently.  If you want to do that, you can send it to avery.schmavery@gmail.com

**Comment by seanballais** [comment] 2016-03-05 11:47
Hi @Schmavery, yes. I'm receiving the same error. I reinstalled my `node_module` a lot already and still no luck.

**Comment by roman30098** [comment] 2016-03-05 12:06
Still same problem. Tried on 2 OS and 2 fb accounts.
I reinstalled node and npm, then downloaded fb-api again.
I followed node install instruction, so I guess it's not node problem.
Is there in node thing like "cookie on/off switch"?

**Comment by Schmavery** [comment] 2016-03-05 22:23
As I said above, we can't reproduce this issue so if you want us to investigate further, someone will need to send the credentials of an account that has problems to the above address.  Thanks :)

**Comment by Schmavery** [comment] 2016-03-06 05:17
Hey Roman, thanks for sending the username/pass, but as I said in the issue, the above credentials work for me and @bsansouci when we try them.  Not sure what we can do.

**Comment by bsansouci** [comment] 2016-03-06 05:29
Hey @roman30098 can you log out of this specific FB account in chrome. When on the login page, open the console go to the network tab, click the record button on the far left (just looks like a grey circle), click on "preserve log" to the right on that same toolbar. Now enter your credentials and hit enter to login. You should see a whole bunch of network stuff happening. Scroll all the way to the top and click on one of the logged network event called "https://www.facebook.com/login.php?login_attempt=1". Now scroll down on the tab that just opened until you hit the "Form Data" section. Can you copy paste this and send it to avery (remove your credentials for there if you want to). That tab that opened will be focused on the "Headers" sub-tab, click on the "Cookies" one and copy paste (or screenshot if you can't copy paste) this part too. That would be tremendous help for us to figure out how to fix this. :D 
Please ask if you have any questions

**Comment by Schmavery** [comment] 2016-04-20 21:14
Closing this for now as no repro

**Closed by Schmavery** 2016-04-20 21:14 UTC
Labels: no repro

**Comment by ppyoosuf** [comment] 2016-08-03 11:42
hai roman30098

your code is running on my system (localhost).

but i have another problem, i have created one fb account and tried to run in mysystem.this is working perfectly on localhost.but i cant run this one in aws.i have installed in my system node version 5.10 but in aws 6.2

**Comment by ppyoosuf** [comment] 2016-08-03 11:43
any problem for version
