### ISSUE TITLE
API breaking after some time?

### ISSUE THREAD

**Issue by p0358** [Schmavery/facebook-chat-api#326] opened 2016-09-08 13:32 UTC
Maybe it was already reported, sorry then, but after some time (about a week), when a bot using this API is launched, this happens:
```
ERR! Error in uploadAttachment Error: form-data: ENOENT: no such file or directory, open '(text message [which the bot was trying to send] content)'
ERR! Error in uploadAttachment   at Error (native)
ERR! Error in uploadAttachment
ERR! Error in uploadAttachment  { Error: form-data: ENOENT: no such file or directory, open '(text message [which the bot was trying to send] content)'
ERR! Error in uploadAttachment   at Error (native)
ERR! Error in uploadAttachment
ERR! Error in uploadAttachment   cause:
ERR! Error in uploadAttachment    { Error: form-data: ENOENT: no such file or directory, open '(text message [which the bot was trying to send] content)'
ERR! Error in uploadAttachment      at Error (native)
ERR! Error in uploadAttachment
ERR! Error in uploadAttachment      errno: -2,
ERR! Error in uploadAttachment      code: 'ENOENT',
ERR! Error in uploadAttachment      syscall: 'open',
ERR! Error in uploadAttachment      path: '(text message [which the bot was trying to send] content)' },
ERR! Error in uploadAttachment   isOperational: true,
ERR! Error in uploadAttachment   errno: -2,
ERR! Error in uploadAttachment   code: 'ENOENT',
ERR! Error in uploadAttachment   syscall: 'open',
ERR! Error in uploadAttachment   path: '(text message [which the bot was trying to send] content)' }
ERR! Error in getUserInfo { error: 'JSON.parse error. Check the `detail` property on this error.',
ERR! Error in getUserInfo   detail:
ERR! Error in getUserInfo    SyntaxError: Unexpected token < in JSON at position 0
ERR! Error in getUserInfo      at Object.parse (native)
ERR! Error in getUserInfo      at /var/www/Concierge/node_modules/facebook-chat-api/utils.js:542:20
ERR! Error in getUserInfo      at tryCatcher (/var/www/Concierge/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in getUserInfo      at Function.Promise.attempt.Promise.try (/var/www/Concierge/node_modules/bluebird/js/main/method.js:31:24)
ERR! Error in getUserInfo      at /var/www/Concierge/node_modules/facebook-chat-api/utils.js:523:24
ERR! Error in getUserInfo      at tryCatcher (/var/www/Concierge/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in getUserInfo      at Promise._settlePromiseFromHandler (/var/www/Concierge/node_modules/bluebird/js/main/promise.js:510:31)
ERR! Error in getUserInfo      at Promise._settlePromiseAt (/var/www/Concierge/node_modules/bluebird/js/main/promise.js:584:18)
ERR! Error in getUserInfo      at Promise._settlePromises (/var/www/Concierge/node_modules/bluebird/js/main/promise.js:700:14)
ERR! Error in getUserInfo      at Async._drainQueue (/var/www/Concierge/node_modules/bluebird/js/main/async.js:123:16)
ERR! Error in getUserInfo      at Async._drainQueues (/var/www/Concierge/node_modules/bluebird/js/main/async.js:133:10)
ERR! Error in getUserInfo      at Immediate.Async.drainQueues (/var/www/Concierge/node_modules/bluebird/js/main/async.js:15:14)
ERR! Error in getUserInfo      at runCallback (timers.js:574:20)
ERR! Error in getUserInfo      at tryOnImmediate (timers.js:554:5)
ERR! Error in getUserInfo      at processImmediate [as _immediateCallback] (timers.js:533:5)
ERR! Error in getUserInfo    ,
ERR! Error in getUserInfo   res: '<html><head><title>Redirecting...</title><script>__DEV__=0;_script_path = "XChatUserInfoAsyncController";var uri_re=/^(?:(?:[^:\\/?#]+):)?(?:\\/\\/(?:[^\\/?#]*))?([^?#]*)(?:\\?([^#]*))?(?:#(.*))?/,target_domain=\'\';window.location.href.replace(uri_re,function(a,b,c,d){var e,f,g;e=f=b+(c?\'?\'+c:\'\');if(d){d=d.replace(/^(!|%21)/,\'\');g=d.charAt(0);if(g==\'/\'||g==\'\\\\\')e=d.replace(/^[\\\\\\/]+/,\'/\');}if(e!=f){if(window._script_path)document.cookie="rdir="+window._script_path+"; path=/; domain="+window.location.hostname.replace(/^.*(\\.facebook\\..*)$/i,\'$1\');window.location.replace(target_domain+e);}});</script><script type="text/javascript">/*<![CDATA[*/(function(){function si_cj(m){setTimeout(function(){new Image().src="https:\\/\\/error.facebook.com\\/common\\/scribe_endpoint.php?c=si_clickjacking&t=4681"+"&m="+m;},5000);}if(top!=self && !false){try{if(parent!=top){throw 1;}var si_cj_d=["apps.facebook.com","apps.beta.facebook.com"];var href=top.location.href.toLowerCase();for(var i=0;i<si_cj_d.length;i++){if (href.indexOf(si_cj_d[i])>=0){throw 1;}}si_cj("3 https:\\/\\/www.facebook.com\\/");}catch(e){si_cj("1 \\thttps:\\/\\/www.facebook.com\\/");window.document.write("\\u003Cstyle>body * {display:none !important;}\\u003C\\/style>\\u003Ca href=\\"#\\" onclick=\\"top.location.href=window.location.href\\" style=\\"display:block !important;padding:10px\\">Menuju Facebook.com\\u003C\\/a>");/*YAjqnClm*/}}}())/*]]>*/</script><script>window.location.replace("https:\\/\\/www.facebook.com\\/common\\/invalid_request.php?__req=61");</script><meta http-equiv="refresh" content="0;url=https://www.facebook.com/common/invalid_request.php?__req=61" /></head><body></body></html>' }
```
And the message wasn't sent of course. Not sure how this API is constructed, but can't it handle these redirects or something?

**Comment by GAMELASTER** [comment] 2016-09-08 14:34
In this time, Facebook changing a lot of things in Messenger, so still is new changes. But, for all people this changes is applying in other days, so for someone can work library without problems, but for someone not.

**Comment by Schmavery** [comment] 2016-09-08 20:16
Probably a duplicate of #202 etc.  Thanks for letting us know.  This is a tricky issue that we haven't been able to get to the bottom of.

**Closed** 2016-09-11 11:16 UTC
Labels: duplicate

**Comment by p0358** [comment] 2016-09-11 12:43
That's another thing that appeared before that error today:

```
ERR! Error in uploadAttachment { __ar: 1,
ERR! Error in uploadAttachment   error: 1357004,
ERR! Error in uploadAttachment   errorSummary: 'Maaf, ada masalah',
ERR! Error in uploadAttachment   errorDescription: 'Coba tutup lalu buka kembali jendela browser Anda.',
ERR! Error in uploadAttachment   payload: null,
ERR! Error in uploadAttachment   bootloadable: {},
ERR! Error in uploadAttachment   ixData: {},
ERR! Error in uploadAttachment   lid: '6329050xxxxxxxxxxxx' }
```
