### ISSUE TITLE
Add guidelines section to README

### ISSUE THREAD

**Issue by mjmohammet** [Schmavery/facebook-chat-api#208] opened 2016-03-18 09:42 UTC
Hi,

Thank you for this interesting repo.

I tried this API on my personal account and another newly created account after several logins I got this error when log out from my personal account (and later on the other newly created account):

`ERR! Error in logout TypeError: Cannot read property '0' of undefined
ERR! Error in logout     at /facebook/node_modules/facebook-chat-api/src/logout.js:18:44
ERR! Error in logout     at tryCatcher (/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in logout     at Promise._settlePromiseFromHandler (/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:507:31)
ERR! Error in logout     at Promise._settlePromiseAt (/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:581:18)
ERR! Error in logout     at Promise._settlePromises (/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:697:14)
ERR! Error in logout     at Async._drainQueue (/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
ERR! Error in logout     at Async._drainQueues (/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
ERR! Error in logout     at Immediate.Async.drainQueues [as _onImmediate] (/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! Error in logout     at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! Error in logout  [TypeError: Cannot read property '0' of undefined]
`

Then I tried to log in and got:
`ERR! Error in login: Couldn't login. Facebook might have blocked this account. Please login with a browser or enable the option 'forceLogin' and try again.`

I opened my account on browser and got this:
![screenshot from 2016-03-18 10 37 38](https://cloud.githubusercontent.com/assets/17661667/13874045/991610e4-ecf5-11e5-879b-2d3b5716829a.png)

From my experience with Facebook I am not optimistic to get my account within weeks from now. I just want to know if this happens to you and what could be a solution to it (the error not Facebook block)? Why Facebook blocked me? is it session/cookies problem?

**Comment by GAMELASTER** [comment] 2016-03-18 10:56
Wow! Interesting. I created few days ago new Facebook account with fake name, anyway not blocked. Then my personal account I used too, and not banned yet. Maybe you get some reports in personal account and because using a library you got banned. My friend got blocked because fake name(not using library), he sent a photo of personal identification card and after day he got account back

**Comment by GAMELASTER** [comment] 2016-03-18 11:00
One more question, you logged still with credentials or your appState? Maybe if you log in with credentials more times in a low range of time, you got blocked.

**Comment by mjmohammet** [comment] 2016-03-18 11:04
mmm.. this is interesting. I am using pure credentials. How can I enable appState instead credentials?

**Comment by GAMELASTER** [comment] 2016-03-18 11:08
https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#login
Little under is example with using appstate

**Comment by Schmavery** [comment] 2016-03-18 18:08
What are you doing with the api?

**Comment by mehcode** [comment] 2016-03-19 15:56
Just want to chime in and say that I can confirm similar behavior if you do NOT use app state. It happens if you login repeatedly. I didn't try to narrow down exact parameters.

**Comment by mjmohammet** [comment] 2016-03-19 19:10
@Schmavery I'm building a bot that responds to questions based on some keywords. It is something for fun and if it is for spamming I would say so.

I doubt that the block is due to multiple sessions opened at the same time as I created two scripts one for each account.

I am going to try the appState. Thanks @GAMELASTER

**Comment by TexAgg** [comment] 2016-03-19 20:52
I have also had the same problem but I just had to enter a confirmation code to prove that I was a human. I think it happens if you log in too much.

**Comment by GAMELASTER** [comment] 2016-03-19 22:57
@mjmohammet I did a similiar bot in a fake profile, all works good, any ban i didnt get yet, and its used alot, so its for appState

**Comment by Schmavery** [comment] 2016-03-19 23:41
Awesome, thanks to everyone for chiming in.  I'm going to close this issue now because it seems like appState is a good workaround.

**Comment by Schmavery** [comment] 2016-03-20 06:26
As a followup, we're planning to add a section to the README with some guidelines to follow to minimize the cases of this happening.  We will recommend the use of appState and remind people to send messages responsibly :)

**Comment by Schmavery** [comment] 2016-03-21 07:29
Reopening as a reminder to add this section.

**Closed** 2016-05-17 07:16 UTC
Labels: update docs
