### ISSUE TITLE
Unable to setTitle of group chat using bot.

### ISSUE THREAD

**Issue by sdj110** [Schmavery/facebook-chat-api#674] opened 2018-08-06 22:41 UTC
Seems that api.SetTitle is giving me some trouble. Although it is a very simple function, I keep getting an error `ERR! setTitle { error: 'Not logged in.' }`. Bot is member and admin of the thread. Any help??

I am just checking for a message event and then calling

api.setTitle("New Title", threadID, (err) =>
        {
            if (err) return console.error(err);

        });

**Comment by ravkr** [comment] 2018-08-06 22:45
Duplicate of #668

**Comment by Schmavery** [comment] 2018-08-21 06:48
Thanks @ravkr 
@sdj110 I'll close this for now to keep the discussion focused in the other issue.

**Closed** 2018-08-21 06:48 UTC
