### ISSUE TITLE
getThreadHistory does not work as intended

### ISSUE THREAD

**Issue by mangopearapples** [Schmavery/facebook-chat-api#447] opened 2017-04-02 01:09 UTC
The `getThreadHistory` function does not appear to be working as the docs describes it to.

The form data for retrieving past messages is:

```
messages[user_ids][threadID][offset]:30
messages[user_ids][threadID][timestamp]:1490908545320
messages[user_ids][threadID][limit]:30
```

From what I observed, it retrieves [limit] amount of messages (+1 sometimes, for some reason :\ ) starting from [timestamp] -> past. 

So a limit of 10 and a timestamp of Date.now() will retrieve the 10 most recent messages.
Or a limit of 10 and a timestamp of 21/12/2015 will retrieve 10 messages from 21/12/2015 -> past.

In order to keep retrieving 10 messages at a time, you would have to use the timestamp of the earliest message from the first query (with timestamp of Date.now()) then query again with a limit of 10 and timestamp of the earliest message timestamp, maybe discarding the first message.

The offset data seems to not really do anything. I reckon it might be for verification purposes however facebook don't really seem to reject the query if the offset is wrong.

Maybe you guys know this already (in which case, sorry for wasting your time) but I think a redesign for the getThreadHistory (or at least a mention in the docs) is necessary. I don't mind doing this.

**Comment by Schmavery** [comment] 2017-04-02 20:31
I think this is a duplicate of #262.  I'd love if someone took the time to figure out the parameters and revamped the whole function.

**Comment by Schmavery** [comment] 2017-04-03 19:56
Closing this because we can continue to track progress in #262

**Closed by Schmavery** 2017-04-03 19:56 UTC
