### ISSUE TITLE
Why this project do not use Zombie instead of request

### ISSUE THREAD

**Issue by tpphu** [Schmavery/facebook-chat-api#42] opened 2015-07-13 04:16 UTC
When I read inside the code of this project, I don't understand one thing:
Why this project do not use Zombie instead of request?

**Comment by bsansouci** [comment] 2015-07-13 04:19
Hey @tpphu, I think we were already talking about this here #37. I'm closing this issue because it's a duplicate of #37.

**Closed by bsansouci** 2015-07-13 04:19 UTC

**Comment by tpphu** [comment] 2015-07-20 08:08
Sorry, I don't know to use Github. Thank so much for your help.
