### ISSUE TITLE
Bot doesn't seem to be automatically responsive to new chats.

### ISSUE THREAD

**Issue by AllanWang** [Schmavery/facebook-chat-api#297] opened 2016-07-08 05:46 UTC
If the bot is added to a new chat, it doesn't seem to register it and won't listen to it until a message is sent through it manually. Prior to a response, I can still trigger sendMessage with the new thread id though.

**Comment by Schmavery** [comment] 2016-07-08 17:55
Does the browser not also behave this way?

**Comment by AllanWang** [comment] 2016-07-17 02:59
I'm not exactly sure how to test this, but if this is the expected result, how do bots typically engage a conversation with a new user without being manually prompted?

**Comment by Schmavery** [comment] 2016-07-17 08:59
Hmm, I think I misunderstood your problem.  Sometimes when my personal account gets added to a thread, I don't get notified until someone sends a message.
You're saying the bot doesn't even listen to messages sent in this new thread until... the bot sends a message to the thread?  Maybe I'm not following.
In any case, on an unrelated note, I'm curious to know why you're trying to use this api for a bot rather than the official one?

**Comment by AllanWang** [comment] 2016-07-17 13:58
Yes that is correct. I have to send a message from the bot before it listens. I'm using this API because the official sdk only supports pages and I therefore can't use it in group chats. I have a lot of features like reminders, text finders, and notifies that are only really useful in groups. Plus with this I can change chat colors, emoji, names etc.

**Comment by AllanWang** [comment] 2016-07-17 13:59
I actually already have a version of the bot with the official sdk, but it's features are much more limited compared to this one

**Comment by Schmavery** [comment] 2016-07-18 07:54
Wow that's crazy, I didn't realise the new official chatbot api doesn't support group chats... that's such a hole.. I can only imagine they must be planning to add it soon.
Anyway, how do you get the thread id of the new chat?  From GetThreadList or something?  Do you mind providing some very small code sample that produces this bug for us to test locally?

**Comment by AllanWang** [comment] 2016-07-18 17:41
Not sure if you are referring to the other issue, but for this one, I expected the bot to listen to new conversations; not sure if it should be expected or not.

I just did some tests though and it is working so now I don't remember if I had to accept an invitation for the other chats or not. I will report back when I get a new issue.

**Comment by Schmavery** [comment] 2016-07-19 01:24
Hmm, ok.  Thanks for following up.  From what I understood, it's not expected behaviour, but if it's because of a message request or something that would maybe explain it.
I was mostly asking how you were making it work in your example (even if it was a workaround).  Just to understand the situation better.
I'll close this for now if it seems like a transient issue but let's keep an eye on this and reopen if necessary.

**Closed by Schmavery** 2016-07-19 01:24 UTC

**Comment by AllanWang** [comment] 2016-07-20 21:08
No workaround. The only way I can respond is if I accept the invitation myself and message. I do believe there were other cases when a one on one conversation that worked before but was silent for a while is no longer listened to, but I will report back when I have a more specific example.
