### ISSUE TITLE
Opening a second listener kills the first one

### ISSUE THREAD

**Issue by nmggithub** [Schmavery/facebook-chat-api#319] opened 2016-08-18 17:21 UTC
I have a function I set up to allow my chat bot to ask a question and then listen to a response. However, this listening requires me to run api.listen again. It works, but after using it my main listener callback doesn't fire anymore. How can I fix this?

**Comment by Schmavery** [comment] 2016-08-18 18:44
Generally we've found that if you're doing it this way, you're probably using the api wrong (feel free to prove me wrong here).
We find that you should run the listener the whole time that the bot is running, and have logic inside the listen callback to filter and handle the messages as desired.  Otherwise you run the risk of missing messages, getting messages twice, and the code gets complicated when you have multiple conversations at the same time.

**Comment by nmggithub** [comment] 2016-08-18 20:03
@Schmavery Hey. Sorry I missed this. All I really want is a second listener to run just long enough to grab one message and then continue on and handle message events regularly. I cannot do this all in one listener as then I would have to reuse code over and over again instead of having a function that runs a second listener for a few seconds. On a slightly-unrelated note, why is this feature not handled with an even emitter?

**Comment by Schmavery** [comment] 2016-08-18 21:08
It just doesn't really make sense to use listen like this, because there's no way to guarantee that the next message will be from a specific person...
I generally don't hear of code reuse being a bad thing ;)  Why can't you have all your main listen logic in a callback that handles and dispatches messages as desired?  Feel free to give some simple code samples of what you're trying to accomplish if you want some pointers on how to do this.
We designed our api in an attempt to be simple, feel free to wrap the callback structure in whatever you feel most comfortable with.

**Comment by nmggithub** [comment] 2016-08-18 22:35
@Schmavery I understand your concern. The second listener will only be up until it detects a message from the correct person.

**Comment by nmggithub** [comment] 2016-08-18 22:36
As far as code samples go I can show it to you later.

**Comment by Schmavery** [comment] 2016-09-08 20:11
Gonna close this as being by design, feel free to continue conversation here.

**Closed by Schmavery** 2016-09-08 20:11 UTC
Labels: question
