### ISSUE TITLE
Add user to group

### ISSUE THREAD

**Issue by jorgemejia** [Schmavery/facebook-chat-api#235] opened 2016-04-04 15:52 UTC
I´m getting problems with this method. The console response with There was a temporary error , try again.
Error:
#1545012

transientError:
#1

**Comment by Schmavery** [comment] 2016-04-04 16:29
My initial guess is that this is a duplicate of #98.  Can you check whether the user was added even though the error occurred?

**Comment by jorgemejia** [comment] 2016-04-04 16:41
I read about it, is there a way to send message to a user?

**Comment by Schmavery** [comment] 2016-04-04 17:09
`api.sendMessage()`?  I don't understand...

**Comment by jorgemejia** [comment] 2016-04-04 17:22
I loged in with the API and I want to send a message to x user is it possible? I used the method sendMessage but the message appears like self message and I want to send message to 'x' person.

**Comment by Schmavery** [comment] 2016-04-04 18:46
Yes?  Please read the docs and make sure you're sending the message to the correct ID.

**Closed by Schmavery** 2016-04-04 18:46 UTC
