### ISSUE TITLE
Question: Sending and receiving messages as Page

### ISSUE THREAD

**Issue by melvinkcx** [Schmavery/facebook-chat-api#656] opened 2018-06-12 07:25 UTC
This is not an issue, but I can't find any better avenue for this question. I am looking into using this library for some developments. However, there is one question I hope to seek clarification with the community. Is this library still be able to send messages as Facebook Page and listen to 'message received' event as a Page? 

Thanks.

**Comment by ravkr** [comment] 2018-06-12 09:11
Yes, it is
![obraz](https://user-images.githubusercontent.com/3875202/41281205-1b89a02c-6e31-11e8-9034-c537025c3e5b.png)

but you have to use github version (latest fix is not yet on npm)
https://github.com/Schmavery/facebook-chat-api#bleeding-edge

**Comment by Bjornskjald** [comment] 2018-06-14 16:30
Also, duplicate of:
- #609
- #588
- #565 
- #468 

@Schmavery @bsansouci could you look at the issues sometimes? 😕

**Comment by Schmavery** [comment] 2018-06-14 18:21
Hey @Bjornskjald, I've stated in a couple of threads (including one that you linked) that page support hasn't been the biggest priority of this api. The general policy is that there are acceptable official channels for doing things like that and that's ok.
That said, when people submit fixes for page issues, we generally try to review and merge them as we have time. @bsansouci and I both have other commitments as well as this repo and the api is definitely a community effort! It's really thanks to all of you that it still works as well as it does.

Regarding this actual issue, I did publish a couple days ago, so if @ravkr is right and this is fixed, then I'd imagine this can be closed as soon as @melvinkcx can confirm it's working now.

**Comment by Bjornskjald** [comment] 2018-06-14 18:28
Hey, thanks for your response!  
I wasn't writing specifically about the page support issue, but about general issue with issues. There are many issues open since a long time without a response (like #564) or issues probably not related to facebook-chat-api (like #620)...

I know both of you have a private life and maybe not much time for maintaining this project, but if this took me literally 5 minutes to find, it sure won't be so hard for you 😃

**Comment by Schmavery** [comment] 2018-06-14 21:57
One does one's best given the circumstances.
If I see that someone (in the case of #620, ravkr) has given a decent answer, I don't necessarily think it's required that I repeat the same thing (that also applies when I've given an answer earlier in the thread that remains relevant). One example of how we depend on the community. If you see something slipped through the cracks, that's your cue to step in and help haha :)
cheers

**Closed** 2019-05-08 03:27 UTC
