### ISSUE TITLE
I get error message when try to uploading an animated GIF as an attachment

### ISSUE THREAD

**Issue by Konstantinusz** [Schmavery/facebook-chat-api#125] opened 2016-01-01 03:46 UTC
Error message:
```
ERR! Error in uploadAttachment { error: 'JSON.parse error. Check the `detail` property on this error.',
ERR! Error in uploadAttachment   detail: [SyntaxError: Unexpected end of input],
ERR! Error in uploadAttachment   res: '' }
```

My script:
```js
var login = require("facebook-chat-api");
var fs = require('fs')

login({email: "X.X@XX.XX", password: "XXX"}, function(err,api) {
    if(err) return console.error(err);
    var yourID = "9876543219876";
    console.log(__dirname)
    var msg = {
    body: "My first animated gif:",
    attachment: fs.createReadStream(__dirname + '/my_first.gif')
    }
    api.sendMessage(msg, yourID);
});
```

**Comment by bsansouci** [comment] 2016-01-01 20:35
Hey @Konstantinusz, we were able to reproduce this error when uploading a file that was named "X.gif" that really was a text file (aka not actually a gif). We tried with the web UI (messenger.com) and get the same error: a 500 response code from the server.

We tried it with a properly formatted gif and seemed to work fine on our side. Can you double check the gif that you're trying to upload? Also can you try to upload it by hand on Facebook?

**Comment by Konstantinusz** [comment] 2016-01-02 05:45
At first I tried with an 5 MB gif file, I think, it was a valid, I generated with Jasc Animation Shop. The result was the abovementioned error message. Then I tried gif animations generated with FFmpeg, it was much larger in size than 5 MB, up to 20 MB, and there were no error messages with them. However I was able to upload the "erroneous" 5 MB gif animation by plain browser (Chrome) and it workd, it played in the chat window without hitch. I uploaded every gif animation from my VPS, so I think internet connection was fast and stable for uploading.

**Comment by Konstantinusz** [comment] 2016-01-02 06:26
I checked again, there is some problem with that GIF animation, it plays fine in browser when I open it from the disk, or from an imgur.com URL, but can not be uploaded to chat window, even Chrome thow an error message when uploading finishes. Imagemagick command identify also shows it valid file, but it seems somehow it became bogus and I accidentally tried with that the attachment upload feature again and again.

**Comment by Schmavery** [comment] 2016-01-02 16:21
If it isn't working in chrome, this is sounding like a Facebook bug.  It seems strange though.

**Comment by Schmavery** [comment] 2016-01-03 21:04
I'm going to close this for now since we don't seem to have much control over it.

**Closed by Schmavery** 2016-01-03 21:04 UTC
Labels: facebook bug
